# Generated by Django 5.2.6 on 2025-10-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('bicicleta', 'Bicicleta')], max_length=20)),
                ('nombre_dueno', models.CharField(max_length=150, verbose_name='Nombre del dueño')),
                ('documento', models.CharField(max_length=50, verbose_name='Documento')),
                ('placa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Placa')),
                ('serial', models.CharField(blank=True, max_length=80, null=True, verbose_name='Serial (bicicleta)')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('marca', models.CharField(blank=True, max_length=80, null=True, verbose_name='Marca')),
                ('area', models.CharField(choices=[('produccion', 'Producción'), ('administracion', 'Administración'), ('logistica', 'Logística'), ('soplado', 'Soplado')], max_length=30, verbose_name='Área')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='parqueadero.vehiculo')),
            ],
            options={
                'ordering': ['-hora_entrada'],
            },
        ),
    ]
