# Generated by Django 4.2.25 on 2025-10-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='hora_entrada',
            field=models.DateTimeField(),
        ),
    ]
