# Generated by Django 4.2.25 on 2025-10-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0002_alter_registro_hora_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='placa',
            field=models.CharField(default='', help_text='Placa del vehículo o serial de bicicleta', max_length=80, verbose_name='Placa/Serial'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
