# Generated by Django 4.2.25 on 2025-10-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0003_registro_placa_alter_registro_hora_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='serial',
        ),
        migrations.AlterField(
            model_name='registro',
            name='placa',
            field=models.CharField(default='', help_text='Placa del vehículo', max_length=80, verbose_name='Placa'),
        ),
    ]
